/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AssisterInputChangeEventDetail,
} from './interfaces';


export namespace Components {
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface AppTest {}
  interface AssisterChat {}
  interface AssisterConversation {
    'insertToBottom': (content: any) => Promise<unknown>;
    'insertToTop': (content: any) => Promise<void>;
  }
  interface AssisterFab {}
  interface AssisterInput {}
  interface AssisterMessage {
    'alignment': 'left' | 'right';
    'status': 'none' | 'pending' | 'sent' | 'delivered';
    'triangle': 'none' | 'top' | 'bottom';
  }
}

declare global {


  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTestElement extends Components.AppTest, HTMLStencilElement {}
  var HTMLAppTestElement: {
    prototype: HTMLAppTestElement;
    new (): HTMLAppTestElement;
  };

  interface HTMLAssisterChatElement extends Components.AssisterChat, HTMLStencilElement {}
  var HTMLAssisterChatElement: {
    prototype: HTMLAssisterChatElement;
    new (): HTMLAssisterChatElement;
  };

  interface HTMLAssisterConversationElement extends Components.AssisterConversation, HTMLStencilElement {}
  var HTMLAssisterConversationElement: {
    prototype: HTMLAssisterConversationElement;
    new (): HTMLAssisterConversationElement;
  };

  interface HTMLAssisterFabElement extends Components.AssisterFab, HTMLStencilElement {}
  var HTMLAssisterFabElement: {
    prototype: HTMLAssisterFabElement;
    new (): HTMLAssisterFabElement;
  };

  interface HTMLAssisterInputElement extends Components.AssisterInput, HTMLStencilElement {}
  var HTMLAssisterInputElement: {
    prototype: HTMLAssisterInputElement;
    new (): HTMLAssisterInputElement;
  };

  interface HTMLAssisterMessageElement extends Components.AssisterMessage, HTMLStencilElement {}
  var HTMLAssisterMessageElement: {
    prototype: HTMLAssisterMessageElement;
    new (): HTMLAssisterMessageElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-test': HTMLAppTestElement;
    'assister-chat': HTMLAssisterChatElement;
    'assister-conversation': HTMLAssisterConversationElement;
    'assister-fab': HTMLAssisterFabElement;
    'assister-input': HTMLAssisterInputElement;
    'assister-message': HTMLAssisterMessageElement;
  }
}

declare namespace LocalJSX {
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'name'?: string;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppTest extends JSXBase.HTMLAttributes<HTMLAppTestElement> {}
  interface AssisterChat extends JSXBase.HTMLAttributes<HTMLAssisterChatElement> {}
  interface AssisterConversation extends JSXBase.HTMLAttributes<HTMLAssisterConversationElement> {}
  interface AssisterFab extends JSXBase.HTMLAttributes<HTMLAssisterFabElement> {}
  interface AssisterInput extends JSXBase.HTMLAttributes<HTMLAssisterInputElement> {
    'onSend'?: (event: CustomEvent<AssisterInputChangeEventDetail>) => void;
  }
  interface AssisterMessage extends JSXBase.HTMLAttributes<HTMLAssisterMessageElement> {
    'alignment'?: 'left' | 'right';
    'status'?: 'none' | 'pending' | 'sent' | 'delivered';
    'triangle'?: 'none' | 'top' | 'bottom';
  }

  interface IntrinsicElements {
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'app-test': AppTest;
    'assister-chat': AssisterChat;
    'assister-conversation': AssisterConversation;
    'assister-fab': AssisterFab;
    'assister-input': AssisterInput;
    'assister-message': AssisterMessage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


