/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  AssisterInputChangeEventDetail,
  IncomingEventDetail,
  MessageDirection,
  MessageState,
  MessageTriangle,
} from './interfaces';

export namespace Components {
  interface ChatCheckMark {
    'ticks': 'one' | 'two';
  }
  interface ChatConversation {
    'scrollToBottom': () => Promise<void>;
  }
  interface ChatInput {}
  interface ChatMessage {
    'direction': MessageDirection;
    'footer': string;
    'state': MessageState;
    'triangle': MessageTriangle;
  }
  interface ChatMessageStatus {
    'state': MessageState;
  }
  interface ChatPane {
    'addCard': ({ text, image }: { text?: string; image?: string; }) => Promise<HTMLElement>;
    'addIncomingMessage': (text: string) => Promise<HTMLElement>;
    'addOutgoingMessage': (text: string) => Promise<HTMLElement>;
    'mapInputTextToHtmlElements': (text: string) => HTMLElement[];
    'triangle': MessageTriangle;
  }
  interface FabApp {
    'close': () => Promise<void>;
    'ionicon': string;
  }
}

declare global {


  interface HTMLChatCheckMarkElement extends Components.ChatCheckMark, HTMLStencilElement {}
  var HTMLChatCheckMarkElement: {
    prototype: HTMLChatCheckMarkElement;
    new (): HTMLChatCheckMarkElement;
  };

  interface HTMLChatConversationElement extends Components.ChatConversation, HTMLStencilElement {}
  var HTMLChatConversationElement: {
    prototype: HTMLChatConversationElement;
    new (): HTMLChatConversationElement;
  };

  interface HTMLChatInputElement extends Components.ChatInput, HTMLStencilElement {}
  var HTMLChatInputElement: {
    prototype: HTMLChatInputElement;
    new (): HTMLChatInputElement;
  };

  interface HTMLChatMessageElement extends Components.ChatMessage, HTMLStencilElement {}
  var HTMLChatMessageElement: {
    prototype: HTMLChatMessageElement;
    new (): HTMLChatMessageElement;
  };

  interface HTMLChatMessageStatusElement extends Components.ChatMessageStatus, HTMLStencilElement {}
  var HTMLChatMessageStatusElement: {
    prototype: HTMLChatMessageStatusElement;
    new (): HTMLChatMessageStatusElement;
  };

  interface HTMLChatPaneElement extends Components.ChatPane, HTMLStencilElement {}
  var HTMLChatPaneElement: {
    prototype: HTMLChatPaneElement;
    new (): HTMLChatPaneElement;
  };

  interface HTMLFabAppElement extends Components.FabApp, HTMLStencilElement {}
  var HTMLFabAppElement: {
    prototype: HTMLFabAppElement;
    new (): HTMLFabAppElement;
  };
  interface HTMLElementTagNameMap {
    'chat-check-mark': HTMLChatCheckMarkElement;
    'chat-conversation': HTMLChatConversationElement;
    'chat-input': HTMLChatInputElement;
    'chat-message': HTMLChatMessageElement;
    'chat-message-status': HTMLChatMessageStatusElement;
    'chat-pane': HTMLChatPaneElement;
    'fab-app': HTMLFabAppElement;
  }
}

declare namespace LocalJSX {
  interface ChatCheckMark {
    'ticks'?: 'one' | 'two';
  }
  interface ChatConversation {}
  interface ChatInput {
    'onSend'?: (event: CustomEvent<AssisterInputChangeEventDetail>) => void;
  }
  interface ChatMessage {
    'direction'?: MessageDirection;
    'footer'?: string;
    'state'?: MessageState;
    'triangle'?: MessageTriangle;
  }
  interface ChatMessageStatus {
    'state'?: MessageState;
  }
  interface ChatPane {
    'mapInputTextToHtmlElements'?: (text: string) => HTMLElement[];
    'onIncoming'?: (event: CustomEvent<IncomingEventDetail>) => void;
    'triangle'?: MessageTriangle;
  }
  interface FabApp {
    'ionicon'?: string;
  }

  interface IntrinsicElements {
    'chat-check-mark': ChatCheckMark;
    'chat-conversation': ChatConversation;
    'chat-input': ChatInput;
    'chat-message': ChatMessage;
    'chat-message-status': ChatMessageStatus;
    'chat-pane': ChatPane;
    'fab-app': FabApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'chat-check-mark': LocalJSX.ChatCheckMark & JSXBase.HTMLAttributes<HTMLChatCheckMarkElement>;
      'chat-conversation': LocalJSX.ChatConversation & JSXBase.HTMLAttributes<HTMLChatConversationElement>;
      'chat-input': LocalJSX.ChatInput & JSXBase.HTMLAttributes<HTMLChatInputElement>;
      'chat-message': LocalJSX.ChatMessage & JSXBase.HTMLAttributes<HTMLChatMessageElement>;
      'chat-message-status': LocalJSX.ChatMessageStatus & JSXBase.HTMLAttributes<HTMLChatMessageStatusElement>;
      'chat-pane': LocalJSX.ChatPane & JSXBase.HTMLAttributes<HTMLChatPaneElement>;
      'fab-app': LocalJSX.FabApp & JSXBase.HTMLAttributes<HTMLFabAppElement>;
    }
  }
}


